<!DOCTYPE html>
<html>
<head>
<title><?=$meta->title?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baseUrl" content="<?=HOST?>" />
<meta name="themeUrl" content="<?=$this->options->themeUrl?>" />
<?php $this->writeMeta(); ?>
<?php Plugin::triggerEvent('theme.head'); ?>
<link rel="shortcut icon" type="image/x-icon" href="<?=$this->options->themeUrl?>/images/favicon.ico" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/main.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/pages.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/responsive.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/videojs-sublime-skin.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Annotator -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
        <script src="http://assets.annotateit.org/annotator/v1.2.5/annotator-full.min.js"></script>
        <link rel="stylesheet" href="http://assets.annotateit.org/annotator/v1.2.5/annotator.min.css">

<!--RangeSlider Pluging-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.1.1/rangeslider.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/rangeslider.js/2.1.1/rangeslider.min.css">

<!--Annotations Pluging-->
        <link rel="stylesheet" type="text/css" href="<?=$this->options->themeUrl?>/css/annotator.min.css" />

<?php $this->writeCSS(); ?>

</head>
<body class="<?=$this->cssHooks()?>">
<?php Plugin::triggerEvent('theme.body'); ?>
    
<?php $this->block('header.phtml'); ?>
    
<div class="container">
    <div class="row">

        <!-- BEGIN MAIN CONTENT -->
        <main class="col-md-8">
            <?=$this->body()?>
        </main>
        <!-- END MAIN CONTENT -->
                
        <div class="sidebar hidden-xs hidden-sm col-md-4">
            <?php $this->writeSidebarBlocks(); ?>
            <?php $this->block('ad300.phtml'); ?>
        </div>

    </div>
</div>

<?php $this->block('footer.phtml'); ?>
    
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/general.js"></script>
<script type="text/javascript" src="<?=$this->options->themeUrl?>/js/annotator.min.js"></script>
<?php $this->writeJs(); ?>

</body>
</html>
